
Neos:
  Flow:
    http:
      chain:
        process:
          chain:
            detectLanguage:
              component: Axovis\Neos\LanguageDetection\LanguageDetectionComponent
              componentOptions:
                ignoreSegments:
                  - neos
                  - 'neos!'
                  - setup
                  - _Resources
                  - media
                allowedMethods:
                  - GET
